### PR TITLE
add elastica bundle

### PR DESCRIPTION
**Pull request by nicolasThal**

### CODE REVIEW

**Comment by itkg-alavieille** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
@itkg-ngilain @itkg-alavieille I have updated the pr

**Comment by itkg-alavieille** [comment]
:+1:

**Comment by SOLenG** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
:+1:

**Pull request merged**
