### PR TITLE
doc for fieldType

### PR DESCRIPTION
**Pull request by itkg-nanne**

### CODE REVIEW

**Comment by juchi** [comment]
Is this PR still going on ? If so, we should move it to the docs project.
Ping @itkg-nanne

**Comment by itkg-ngilain** [comment]
@itkg-nanne : toujours d'actualité ?

**Comment by nicolasThal** [comment]
I think that this doc should be moved to the open-orchestra-docs repository

**Comment by itkg-ngilain** [comment]
@itkg-nanne , @itkg-alavieille : Maybe we can close that one now ?

**Comment by itkg-alavieille** [comment]
https://github.com/open-orchestra/open-orchestra-docs/blob/master/en/developer_guide/field_type.rst

**Pull request closed without merging**
