### PR TITLE
matrix mongo version

### PR DESCRIPTION
**Pull request by itkg-alavieille**
fix quote

### CODE REVIEW

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
:+1:

**Comment by nicolasThal** [comment]
At one time, we could check how to migrate to container build : http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by itkg-alavieille** [comment]
@nicolasThal yes I saw but in the infrastructure, there is more access to sudo to install the packages there are solutions, but to create the ``uploaded-files`` must be put elsewhere than in ``/var``, i create a ticket for it

**Pull request merged**
