### PR TITLE
varnish conf for load balancing

### PR DESCRIPTION
**Pull request by itkg-rboessel**

### CODE REVIEW

**Comment by itkg-rboessel** [comment]
https://github.com/open-orchestra/open-orchestra/pull/613
https://github.com/open-orchestra/open-orchestra/pull/615
open-orchestra/open-orchestra-front-demo#82
https://github.com/open-orchestra/open-orchestra-provision/pull/16

**Comment by itkg-rboessel** [comment]
https://github.com/open-orchestra/open-orchestra-front-demo/pull/84

**Comment by itkg-rboessel** [comment]
@nicolasThal @itkg-alavieille

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
