### PR TITLE
add jmeter test routing

### PR DESCRIPTION
**Pull request by itkg-alavieille**
scenario:

two user groups:
- first, they take a node in the csv file, created a new version and publishes it
- second group, choice a node in the csv and goes on his pattern in front

### CODE REVIEW

**Comment by nicolasThal** [comment]
Instead of going on the admin page, have you tried to make a direct call to the api to create a new version ?

That could be easier to load !

**Comment by itkg-ngilain** [comment]
Doing this, you don't charge the Back Office. It's possible but what will be the purpose of the test ?

**Comment by nicolasThal** [comment]
I think that the pupose of the test is to charge the front and see the impact of the routing cache file suppression

**Comment by itkg-ngilain** [comment]
Ok, in that case I agree with you :)

**Comment by itkg-alavieille** [comment]
@nicolasThal @itkg-ngilain done

**Comment by nicolasThal** [comment]
:+1: do you have a visual result of the test?

**Comment by itkg-alavieille** [comment]
currently, Currently, there are 0% error in front but it is not representative because the publication of several node stops very quickly with the problem with many node with same version.

**Pull request merged**
