### PR TITLE
update gruntfile to add user.coffee

### PR DESCRIPTION
**Pull request by itkg-rboessel**

### CODE REVIEW

**Comment by itkg-rboessel** [comment]
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/51
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/777

**Comment by nicolasThal** [comment]
:+1: but this pr should be merged after the two others

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
@itkg-rboessel : are you still working on that PR ?

**Pull request merged**
